### ISSUE TITLE
I can't find these installation packages.

### ISSUE THREAD

**Issue by ztaozhang** [cneira/zcage#19]
pkg install system/zones/brand/bhyve
pkg install brand/pkgsrc 

root@026:~# pkg install system/zones/brand/bhyve

pkg install: The following pattern(s) did not match any allowable packages.  Try
using a different matching pattern, or refreshing publisher information:

        system/zones/brand/bhyve
root@026:~# pkg install brand/pkgsrc 

pkg install: The following pattern(s) did not match any allowable packages.  Try
using a different matching pattern, or refreshing publisher information:

        brand/pkgsrc
root@026:~# 

I can't find these installation packages.

**Comment by moetiker** [comment]
Are you using version 28 of http://omniosce.org

**Comment by ztaozhang** [comment]
You mean that the omnios-r151028 version works？

**Comment by moetiker** [comment]
yes, for me it works...

**Comment by cneira** [comment]
@ztaozhang 
Have you tried with omnios-r151028? , the package is available in that version. I'll update the documentation to make reference to the minimum omniosce version needed to run zcage.
