### ISSUE TITLE
Zcage activation also does not work

### ISSUE THREAD

**Issue by ztaozhang** [cneira/zcage#20]
root@026:~/zcage# zcage activate
Did you run zcage activate?
You need to install the following packages:
pkg install pkg:/system/zones/brand/lx
pkg install system/bhyve
pkg install system/zones/brand/bhyve
pkg install brand/pkgsrc
pkg install brand/sparse
Activating zcage wait a few seconds...
root@026:~/zcage# zcage images --list
Did you run zcage activate?
You need to install the following packages:
pkg install pkg:/system/zones/brand/lx
pkg install system/bhyve
pkg install system/zones/brand/bhyve
pkg install brand/pkgsrc
pkg install brand/sparse
root@napp-it-026:~/zcage#

**Comment by cneira** [comment]
@ztaozhang 
Have you installed the required packages and then run zcage activate?

**Comment by cneira** [comment]
I'm closing this as it seems you are already creating zones.
