### ISSUE TITLE
 Vm can not be started, dmesg information is as follows

### ISSUE THREAD

**Issue by ztaozhang** [cneira/zcage#22]
omniosce ip: [ID 146484 kern.notice] ip_loopback_removeif: IPv6 SIOCLIFREMOVEIF failed: error 1
Apr 14 23:45:26 omniosce ip: [ID 146484 kern.notice] ip_loopback_removeif: IPv4 SIOCLIFREMOVEIF failed: error 1
Apr 14 23:45:34 omniosce ip: [ID 146484 kern.notice] ip_loopback_removeif: IPv6 SIOCLIFREMOVEIF failed: error 1
Apr 14 23:45:34 omniosce ip: [ID 146484 kern.notice] ip_loopback_removeif: IPv4 SIOCLIFREMOVEIF failed: error 1
Apr 14 23:45:36 omniosce ip: [ID 146484 kern.notice] ip_loopback_removeif: IPv6 SIOCLIFREMOVEIF failed: error 1
Apr 14 23:45:36 omniosce ip: [ID 146484 kern.notice] ip_loopback_removeif: IPv4 SIOCLIFREMOVEIF failed: error 1

**Comment by cneira** [comment]
Could you try: 
```bash
# zoneadm -z <zonename> boot 
```

**Comment by cneira** [comment]
I'm going to close this one, feel to reopen is the issue is still present.
