### ISSUE TITLE
zcage activate: You must specify a pool to use

### ISSUE THREAD

**Issue by drscream** [cneira/zcage#23]
### Version

```
1.4.7
```

### Command

```
zcage activate
```

### Output

```
Did you run zcage activate?
You need to install the following packages:
pkg install pkg:/system/zones/brand/lx
pkg install system/bhyve
pkg install system/zones/brand/bhyve
pkg install brand/pkgsrc
pkg install brand/kvm
pkg install brand/kvm-driver
pkg install brand/sparse
You must specify a pool to use for zone and images datasets
```

### Comment

All required packages are installed, I tried to run the commend in the global zone and I'm also able to create bhyve zones manually.

I'm not an nodejs expert but shouldn't the function `ActivateZcage()` be called with a pool name?

https://github.com/cneira/zcage/blob/master/zcage#L309

**Comment by cneira** [comment]
You are right, I'm sorry, I was refactoring so users could specify which pool to use when activating zcage, by a config file, but seems I have not completed this.
Could you use release version [1.4.6](https://github.com/cneira/zcage/archive/1.4.6.tar.gz) in the meantime?. I'll have it fixed tomorrow.

**Comment by cneira** [comment]
This should be fixed now in Master branch. 
zcage activate now could specify in which pool to store zcage data. 
```
$ pfexec zcage activate --pool rpool 
```
Feel free to reopen if this persists.

**Comment by drscream** [comment]
Thanks a lot for your fast reply. The following error / info is only shown, if I try to activate the pool:

```
zcage is already activated using pool :rpool
```
