### ISSUE TITLE
npm WARN lifecycle dtrace-provider@0.8.7~install: cannot run in wd dtrace-provider

### ISSUE THREAD

**Issue by liv3010m** [cneira/zcage#25]
At the end of the install it complains with a warning, is it OK?

`srv-omnios% git clone https://github.com/cneira/zcage.git && cd zcage && pfexec npm install -g`
`Cloning into 'zcage'...`
`remote: Enumerating objects: 211, done.`
`remote: Counting objects: 100% (211/211), done.`
`remote: Compressing objects: 100% (140/140), done.`
`remote: Total 7228 (delta 127), reused 150 (delta 69), pack-reused 7017`
`Receiving objects: 100% (7228/7228), 24.45 MiB | 852.00 KiB/s, done.`
`Resolving deltas: 100% (2038/2038), done.`
`/opt/ooce/node-10/bin/jq-solaris11-64 -> /opt/ooce/node-10/lib/node_modules/zcage/tools/jq-solaris11-64`
`/opt/ooce/node-10/bin/list-tags.sh -> /opt/ooce/node-10/lib/node_modules/zcage/tools/list-tags.sh`
`/opt/ooce/node-10/bin/zcage -> /opt/ooce/node-10/lib/node_modules/zcage/zcage`
`/opt/ooce/node-10/bin/pull-by-tag.sh -> /opt/ooce/node-10/lib/node_modules/zcage/tools/pull-by-tag.sh`
`/opt/ooce/node-10/bin/bhyve-zvol.sh -> /opt/ooce/node-10/lib/node_modules/zcage/tools/bhyve-zvol.sh`
`/opt/ooce/node-10/bin/cloud-init.sh -> /opt/ooce/node-10/lib/node_modules/zcage/tools/cloud-init.sh
npm WARN lifecycle dtrace-provider@0.8.7~install: cannot run in wd dtrace-provider@0.8.7 node-gyp rebuild || node suppress-error.js (wd=/home/username/zcage/node_modules/dtrace-provider)`
`+ zcage@1.4.7`
`added 612 packages from 1057 contributors in 31.257s`

**Comment by cneira** [comment]
@liv3010m  yes, zcage is not using dtrace at this point.
