### ISSUE TITLE
Can't activate zcage

### ISSUE THREAD

**Issue by liv3010m** [cneira/zcage#26]
OS: omnios-r151030-632fca26eb
zcage version: 1.4.7

`root@srv-omnios:/home/username# /opt/ooce/node-10/bin/zcage`  

`Options:`
`-----------------------`
`create:  Creates a zone.`
`start:   Starts a zone`
`stop:    Stops a zone`
`images:  List available images`
`pull:    Download images`
`destroy: Destroys a zone`
`update:  Updates zone resources`
`version: Prints zcage version`
`fetch:   Downloads an image from url for later use (lx,bhyve and kvm brands)`

`For help on a specific command type zcage help <Option>`

`Examples:`

`To create a zone with 2gb of ram using with ip address/mask 192.168.1.225/24 and gateway 192.168.1.1:`

`# zcage create --net "vnic0|192.168.1.225/24|192.168.1.1" --ram 2gb`

`root@srv-omnios:/home/username# /opt/ooce/node-10/bin/zcage activate`
`Did you run zcage activate?`
`You need to install the following packages:`
`pkg install pkg:/system/zones/brand/lx`
`pkg install system/bhyve`
`pkg install system/zones/brand/bhyve`
`pkg install brand/pkgsrc`
`pkg install brand/kvm`
`pkg install brand/kvm-driver`
`pkg install brand/sparse`
`zcage is already activated using pool :rpool`

`root@srv-omnios:/home/username# /opt/ooce/node-10/bin/zcage images --list`
`Did you run zcage activate?`
`You need to install the following packages:`
`pkg install pkg:/system/zones/brand/lx`
`pkg install system/bhyve`
`pkg install system/zones/brand/bhyve`
`pkg install brand/pkgsrc`
`pkg install brand/kvm`
`pkg install brand/kvm-driver`
`pkg install brand/sparse`

`root@srv-omnios:/home/username# pkg list cdrtools`
`NAME (PUBLISHER)                                  VERSION                    IFO`
`media/cdrtools                                    3.1-151030.0               i--`
`root@srv-omnios:/home/username# pkg list brand/bhyve`
`NAME (PUBLISHER)                                  VERSION                    IFO`
`system/zones/brand/bhyve                          0.5.11-151030.0            i--`
`root@srv-omnios:/home/username# pkg list brand/kvm`
`NAME (PUBLISHER)                                  VERSION                    IFO`
`system/zones/brand/kvm                            0.5.11-151030.0            i--`
`root@srv-omnios:/home/username# pkg list brand/lx `
`NAME (PUBLISHER)                                  VERSION                    IFO`
`system/zones/brand/lx                             0.5.11-151030.0            i--`
`root@srv-omnios:/home/username# pkg list brand/pkgsrc`
`NAME (PUBLISHER)                                  VERSION                    IFO`
`system/zones/brand/pkgsrc                         0.5.11-151030.0            i--`
`root@srv-omnios:/home/username# pkg list brand/sparse`
`NAME (PUBLISHER)                                  VERSION                    IFO`
`system/zones/brand/sparse                         0.5.11-151030.0            i--`
`root@srv-omnios:/home/username# pkg list brand/lipkg `
`NAME (PUBLISHER)                                  VERSION                    IFO`
`system/zones/brand/lipkg                          0.5.11-151030.0            i--`
`root@srv-omnios:/home/username# pkg list system/kvm `
`NAME (PUBLISHER)                                  VERSION                    IFO`
`system/kvm                                        1.0.5.11-151030.0          i--`

Don't know how to get around this.

Any help would be appreciated.

**Comment by cneira** [comment]
I'm sorry I'll take a look. I'm not receiving the email notifications.
In the meantime, have you tried running the last release ? https://github.com/cneira/zcage/releases/tag/1.4.6

**Comment by cneira** [comment]
@liv3010m 
Could you pull from master and try again ?
```
cneira@Trixie:~/zcage-next$ pfexec ./zcage activate --pool rpool
Activating zcage wait a few seconds...
pool is from config: rpool
Using pool: rpool
Creating rpool/zcage
Creating rpool/zcage/vms
Creating rpool/zcage/images
````

**Comment by liv3010m** [comment]
Hi Carlos,

Thanks for the answer.
I'll try in something like one hour and report back!
Am 25. Juni 2019, 13:21 -0300 schrieb Carlos Neira <notifications@github.com>:

**Comment by cneira** [comment]
@liv3010m  Let me know if still does not work I will fix it today.
I'm sorry for the inconvenience.

**Comment by liv3010m** [comment]
Hi Carlos!

`root@srv-omnios:/home/username/zcage# git pull`
`remote: Enumerating objects: 65, done.`
`remote: Counting objects: 100% (59/59), done.`
`remote: Compressing objects: 100% (27/27), done.`
`remote: Total 44 (delta 32), reused 28 (delta 17), pack-reused 0`
`Unpacking objects: 100% (44/44), done.`
`From https://github.com/cneira/zcage`
`   07ce7da..a61c137  master     -> origin/master`
`Updating 07ce7da..a61c137`
`Fast-forward`
` docs/basic-use.md    |  6 +++++-`
` docs/brand-types.md  |  8 ++++----`
` docs/install.md      | 25 +++++++++++--------------`
` docs/quickstart.md   |  2 +-`
` lib/imgadm.js        | 14 ++++++++++----`
` tools/pull-by-tag.sh |  9 +++++----`
` zcage                | 21 +++++++++++++--------`
` 7 files changed, 49 insertions(+), 36 deletions(-)`

`root@srv-omnios:/home/username/zcage# ./zcage activate --pool rpool`
`Activating zcage wait a few seconds...`
`pool is from config: rpool`
`Using pool: rpool`
`Creating rpool/zcage`
`Creating rpool/zcage/vms`
`Creating rpool/zcage/images`

`root@srv-omnios:/home/maleficent/zcage# ./zcage images --list proxmox`
`Proxmox Available images`
`-------------------------`
`alpine-3.7-default_20180913_amd64.tar.xz`
`alpine-3.8-default_20180913_amd64.tar.xz`
...
`ubuntu-18.10-standard_18.10-1_amd64.tar.gz`
`ubuntu-18.10-standard_18.10-2_amd64.tar.gz`

Seems to work! :)
I'll try more tomorrow!

**Comment by cneira** [comment]
@liv3010m  I'll close this one tomorrow, feel free to reopen if needed.
Thanks for testing this out.
