### ISSUE TITLE
Not all docker containers work

### ISSUE THREAD

**Issue by bhechinger** [cneira/zcage#30]
Using zcage 1.4.6 I get this trying to deploy nexus

```
wonko@basket:~/zcage$ zcage create --net "nexus3|10.42.2.23/24|10.42.2.252" --docker sonatype/nexus3 --alias nexus3 --brand lx
Error: Installing zone nexus3
Failed creating zone:  nexus3
```

Is there a way to get better logs to figure out what's gone wrong?

**Comment by cneira** [comment]
I'll take a look.

**Comment by cneira** [comment]
It seems I forgot to add jq to the requeriments I updated the docs, also docker images are pulled using library/name tag, for example  library/alpine latest, in your case is sonatype/nexus3 latest
I updated this on https://github.com/cneira/zcage/commit/733e19f22c90bac8f2e2b3c15dd6c5fb2e2feaa7
try this: 
```bash
zcage create --net "vnic0|192.168.1.225/24|192.168.1.1" --docker sonatype/nexus3 latest --alias nexus3 --brand lx
```
Feel free to re-open if needed.
