### ISSUE TITLE
add option to create zone in stopped state

### ISSUE THREAD

**Issue by bhechinger** [cneira/zcage#33]
I have some steps I'd like to perform to the zone filesystem before booting it for the first time. It would be really nice if there was an option to create a zone in a stopped state so I could perform those actions before booting it.

Thanks!

**Comment by cneira** [comment]
@bhechinger I agree mostly my uses cases don't involve doing more changes on the zone after creation. Now zones won't auto start after creation so users could perform any needed change before starting them.

**Comment by bhechinger** [comment]
Is there a new flag for this? It still seems to start them immediately after creating them.

**Comment by cneira** [comment]
Hi,

For native and lx zones, they will not start after creation, there is no
flag.

Bests

**Comment by bhechinger** [comment]
I didn't start it, it's running though. So I don't think that's working the way you hoped?

```Setting quota=10G on dataset rpool/zcage/vms/minecraft0
minecraft0 created [OK] 
minecraft0 started [OK] 
wonko@basket:~/lx_images$ zcage list
UUID					 TYPE	STATE	 ALIAS
4d2e4c18-1c78-4b9b-ff03-a613f0b87a2a	 LX	running	plex0
688dba56-106a-6202-8915-e11513c2367d	 LX	running	transmission
e31dd9c8-9595-e037-94a6-a9d9cf1a3229	 LX	running	traefik0
cf7ecfe0-594e-eb79-bfc1-9921074b4139	 BHYVE	running	tritonheadnode0
3f69d2f7-e66a-6172-c4e5-dc4ae686f501	 LX	running	nexus3
d2c69dc7-3f0f-ed3b-88bd-a75866e44c62	 LX	running	minecraft0
```

Or did I fail to properly update the insatlled zcage?

**Comment by bhechinger** [comment]
Nevermind, I botched the upgrade
