### ISSUE TITLE
Zcage: images reporting no data for joynet

### ISSUE THREAD

**Issue by psammarco** [cneira/zcage#38]
Hello,

I a using Zcage 1.4.7 on omnios-r151032-19f7bd2ae5 and I noticed "images --list joynet" will produce no output whatsoever, while both proxmox and docker options do work just fine.

I took a trace with truss in hope it will shed some light. 

Thanks,
Pietro

[trace.txt](https://github.com/cneira/zcage/files/4129128/trace.txt)

**Comment by cneira** [comment]
Have you tried  --list joyent ?

**Comment by cneira** [comment]
try with --list joyent if still does not work, please re-open.
