### ISSUE TITLE
cloud-init qcow version 3 support

### ISSUE THREAD

**Issue by MarkProminic** [cneira/zcage#45]
Hello again,

After pulling the image successfully, thank you for the hasty fix!, I was trying to set up the latest version of CentOS 7 provided by cloud-init with the following command:

zcage create --debug --net="vnic0|192.168.2.188/24|192.168.2.1" --brand bhyve --alias cloud-init --with-image=CentOS-7-x86_64-GenericCloud-2003.qcow2.xz  --udata=/tmp/auth

But I get this error:

![image](https://user-images.githubusercontent.com/50398495/81590366-520e7e80-9380-11ea-97ba-65998276bb3e.png)

> bhyve-zvol stdout:Error:errcode: 1 reason: stderr: qemu-img: 'image' uses a qcow2 feature which is not supported by this qemu version: QCOW version 3
qemu-img: Could not open '/zcage/images/fe962d4a-b22c-6b44-b00f-e064a52e7d61.qcow2': Operation not supported
qemu-img: Could not open '/zcage/images/fe962d4a-b22c-6b44-b00f-e064a52e7d61.qcow2'
Converting to raw qemu-img: 'image' uses a qcow2 feature which is not supported by this qemu version: QCOW version 3
qemu-img: Could not open '/zcage/images/fe962d4a-b22c-6b44-b00f-e064a52e7d61.qcow2': Operation not supported
qemu-img: Could not open '/zcage/images/fe962d4a-b22c-6b44-b00f-e064a52e7d61.qcow2'
Error: Installing zone cloud-init
Failed creating zone:  cloud-init

**Comment by cneira** [comment]
It seems the qemu version does not supports that image is odd, have you
tried an older image?

**Comment by MarkProminic** [comment]
Well, I tried with v1711:

>vm image used for zvol creation: /zcage/images/CentOS-7-x86_64-GenericCloud-1711.qcow2.xz
vm zvol size = 10G
 is cloud init = true
bhyve-zvol stdout:stderr:
cloud-init stdout:





>runcmd :
udata is :


>stderr: /opt/ooce/node-12/bin/cloud-init.sh[23]: jq: not found [No such file or directory]
/opt/ooce/node-12/bin/cloud-init.sh: line 24: : cannot open
/opt/ooce/node-12/bin/cloud-init.sh[28]: jq: not found [No such file or directory]
/opt/ooce/node-12/bin/cloud-init.sh: line 28: jq: not found
/opt/ooce/node-12/bin/cloud-init.sh: line 28: jq: not found
/opt/ooce/node-12/bin/cloud-init.sh[30]: jq: not found [No such file or directory]
/opt/ooce/node-12/bin/cloud-init.sh: line 30: jq: not found
/opt/ooce/node-12/bin/cloud-init.sh: line 30: jq: not found
/opt/ooce/node-12/bin/cloud-init.sh[32]: jq: not found [No such file or directory]
/opt/ooce/node-12/bin/cloud-init.sh: line 32: jq: not found
/opt/ooce/node-12/bin/cloud-init.sh: line 32: jq: not found
/opt/ooce/node-12/bin/cloud-init.sh: line 34: jq: not found
/opt/ooce/node-12/bin/cloud-init.sh[38]: jq: not found [No such file or directory]
/opt/ooce/node-12/bin/cloud-init.sh: line 40: jq: not found
/opt/ooce/node-12/bin/cloud-init.sh: line 40: jq: not found
/opt/ooce/node-12/bin/cloud-init.sh[45]: jq: not found [No such file or directory]
/opt/ooce/node-12/bin/cloud-init.sh[47]: jq: not found [No such file or directory]
/opt/ooce/node-12/bin/cloud-init.sh[49]: jq: not found [No such file or directory]
/opt/ooce/node-12/bin/cloud-init.sh[51]: jq: not found [No such file or directory]
: cannot open
: cannot open
: cannot open
/opt/ooce/node-12/bin/cloud-init.sh: line 84: mkisofs: not found

>Setting up cloud-init data /opt/ooce/node-12/bin/cloud-init.sh[23]: jq: not found [No such file or directory]
/opt/ooce/node-12/bin/cloud-init.sh: line 24: : cannot open
/opt/ooce/node-12/bin/cloud-init.sh[28]: jq: not found [No such file or directory]
/opt/ooce/node-12/bin/cloud-init.sh: line 28: jq: not found
/opt/ooce/node-12/bin/cloud-init.sh: line 28: jq: not found
/opt/ooce/node-12/bin/cloud-init.sh[30]: jq: not found [No such file or directory]
/opt/ooce/node-12/bin/cloud-init.sh: line 30: jq: not found
/opt/ooce/node-12/bin/cloud-init.sh: line 30: jq: not found
/opt/ooce/node-12/bin/cloud-init.sh[32]: jq: not found [No such file or directory]
/opt/ooce/node-12/bin/cloud-init.sh: line 32: jq: not found
/opt/ooce/node-12/bin/cloud-init.sh: line 32: jq: not found
/opt/ooce/node-12/bin/cloud-init.sh: line 34: jq: not found
/opt/ooce/node-12/bin/cloud-init.sh[38]: jq: not found [No such file or directory]
/opt/ooce/node-12/bin/cloud-init.sh: line 40: jq: not found
/opt/ooce/node-12/bin/cloud-init.sh: line 40: jq: not found
/opt/ooce/node-12/bin/cloud-init.sh[45]: jq: not found [No such file or directory]
/opt/ooce/node-12/bin/cloud-init.sh[47]: jq: not found [No such file or directory]
/opt/ooce/node-12/bin/cloud-init.sh[49]: jq: not found [No such file or directory]
/opt/ooce/node-12/bin/cloud-init.sh[51]: jq: not found [No such file or directory]
: cannot open
: cannot open
: cannot open
>/opt/ooce/node-12/bin/cloud-init.sh: line 84: mkisofs: not found
Error: Installing zone cloud-init
Failed creating zone:  cloud-init

**Comment by MarkProminic** [comment]
I had an issue installing cdrtools, and as a result the package jq that was in the oneliner was also not installed. My mistake. I can confirm after install jq the older version booted up.
