### ISSUE TITLE
cloud-init images fail to boot

### ISSUE THREAD

**Issue by MarkProminic** [cneira/zcage#46]
So getting through all the issues here, thank you for your help so far. 

I can now get the image to boot, and I can get into EFI mode, but it doesn't try to boot the OS. Will I need to do the same as the instructions on the bottom of: https://omniosce.org/info/bhyve_kvm_brand suggest?

![image](https://user-images.githubusercontent.com/50398495/81598769-6dcc5180-938d-11ea-8f60-39e658ce1d75.png)

**Comment by cneira** [comment]
@MarkProminic 
Yes that’s right is not finding the boot image.

**Comment by cneira** [comment]
@MarkProminic  Feel free to reopen if needed
