### ISSUE TITLE
listing docker images fails

### ISSUE THREAD

**Issue by redvelociraptor** [cneira/zcage#52]
I've tried to list multiple images from the docker hub repository, and even the example from the docs fails: 
>~/src/zcage/zcage images --list docker library/ubuntu
>Error: spawnSync list-tags.sh ENOENT
>    at Object.spawnSync (internal/child_process.js:1067:20)
>    at spawnSync (child_process.js:602:24)
>    at Object.docker_list (/export/home/redvelociraptor/src/zcage/lib/imgadm.js:452:13)
>    at Object.<anonymous> (/export/home/redvelociraptor/src/zcage/zcage:404:33)
>    at Module._compile (internal/modules/cjs/loader.js:1063:30)
>    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
>    at Module.load (internal/modules/cjs/loader.js:928:32)
>    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
>    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
>    at internal/main/run_main_module.js:17:47 {
>  errno: -2,
>  code: 'ENOENT',
>  syscall: 'spawnSync list-tags.sh',
>  path: 'list-tags.sh',
>  spawnargs: [ 'library/ubuntu' ]
>}

However, if I execute `list-tags.sh` manually, it does work for the doc example e.g.`library/ubuntu`, as well as other examples, such as `library/mongo`, `ebooktools/scripts`.

Unfortunately, I don't know enough about Javascript to be able to grasp this backtrace and debug further.

**Comment by cneira** [comment]
@redvelociraptor  hi, have you tried the latest master?

**Comment by redvelociraptor** [comment]
I'm using version 1.5.0 on OmniOS version omnios-r151036-de483383c0.

**Comment by cneira** [comment]
Try using 1.5.2 from master.

**Comment by redvelociraptor** [comment]
I cloned directly from the repo; git indicates I have origin/master. 
`git show-branch`
`[master] Merge pull request #51 from cneira/dependabot/npm_and_yarn/find-my-way-2.2.5`

This is all I see available for branches:
`git branch -a`
`* master`
`  remotes/origin/HEAD -> origin/master`
`  remotes/origin/dilos`
`  remotes/origin/master`
`  remotes/origin/rest`
`  remotes/origin/updates`
`  remotes/origin/v2`

**Comment by cneira** [comment]
@redvelociraptor  I'm sorry again the last refactoring broke docker support and other brands, now is fixed. let me know if you find more issues.
