### ISSUE TITLE
zcage refuses to write image to configured pool

### ISSUE THREAD

**Issue by redvelociraptor** [cneira/zcage#53]
Working on OmniOS version:
`SunOS rvbox 5.11 omnios-r151036-de483383c0 i86pc i386 i86pc`

zcage refuses to write images to the configured pool using sudo, pfexec, or the root user:
`more /etc/zcage.conf
{
    "pool": "rpool"
}`
>$ ls -altrd /zcage/images
>drwxr-xr-x   2 root     root           2 Feb 26 08:53 /zcage/images/

It always returns the same error:
>pfexec /export/home/redvelociraptor/src/zcage/zcage pull --image 9aa48095-da9d-41ca-a094-31d1fb476b98 --pro
vider joyent
>Not able to store image  9aa48095-da9d-41ca-a094-31d1fb476b98
>User executing zcage must be able to write to /zcage/images or have a Primary Administrator Role
>Maybe type:
>pfexec zcage pull --image 9aa48095-da9d-41ca-a094-31d1fb476b98)

Using `truss` on the command returns F_OK: 
[snipped all previous output from truss]
>/1:     open("/export/home/redvelociraptor/src/zcage/node_modules/command-line-usage/package.json", O_RDONLY|O_CLOEXEC) = 24
>/1:     pread(24, " {\n     " _ f r o m " :".., 32768, 0) = 1871
>/1:     close(24)                                       = 0
>/1:     stat("/export/home/redvelociraptor/src/zcage/node_modules/command-line-usage", 0xFFDF6280) = 0
>/1:     stat("/export/home/redvelociraptor/src/zcage/node_modules/command-line-usage.js", 0xFFDF61B0) Err#2 ENOENT
>/1:     stat("/export/home/redvelociraptor/src/zcage/node_modules/command-line-usage.json", 0xFFDF61B0) Err#2 ENOENT
>/1:     stat("/export/home/redvelociraptor/src/zcage/node_modules/command-line-usage.node", 0xFFDF61B0) Err#2 ENOENT
>/1:     stat("/export/home/redvelociraptor/src/zcage/node_modules/command-line-usage/index.js", 0xFFDF6100) = 0
>/1:     lstat("/export/home/redvelociraptor/src/zcage/node_modules/command-line-usage", 0xFFDF61B0) = 0
>/1:     lstat("/export/home/redvelociraptor/src/zcage/node_modules/command-line-usage/index.js", 0xFFDF61B0) = 0
>/1:     open("/export/home/redvelociraptor/src/zcage/node_modules/command-line-usage/index.js", O_RDONLY|O_CLOEXEC) = 24
>/1:     fstat(24, 0xFFDF65F0)                           = 0
>/1:     read(24, " ' u s e   s t r i c t '".., 5218)    = 5218
>/1:     close(24)                                       = 0
>/1:     mprotect(0xA3842000, 249856, PROT_READ|PROT_WRITE) = 0
>/1:     mprotect(0xA3842000, 249856, PROT_READ|PROT_EXEC) = 0
>/1:     mprotect(0xA3842000, 249856, PROT_READ|PROT_WRITE) = 0
>/1:     mprotect(0xA3842000, 249856, PROT_READ|PROT_EXEC) = 0
>/1:     mprotect(0xA3842000, 249856, PROT_READ|PROT_WRITE) = 0
>/1:     mprotect(0xA3842000, 249856, PROT_READ|PROT_EXEC) = 0
>/1:     mprotect(0xA3842000, 249856, PROT_READ|PROT_WRITE) = 0
>/1:     mprotect(0xA3842000, 249856, PROT_READ|PROT_EXEC) = 0
>/1:     access("/etc/zcage.conf", F_OK)                 = 0
>/1:     access("/zcage", F_OK)                          = 0
>/1:     access("/zcage/images/9aa48095-da9d-41ca-a094-31d1fb476b98.zss.gz", F_OK) Err#2 ENOENT
>/1:     mprotect(0xA3842000, 249856, PROT_READ|PROT_WRITE) = 0
>/1:     mprotect(0xA3842000, 249856, PROT_READ|PROT_EXEC) = 0
>Not able to store image  9aa48095-da9d-41ca-a094-31d1fb476b98
>User executing zcage must be able to write to /zcage/images or have a Primary Administrator Role
>Maybe type:
>pfexec zcage pull --image 9aa48095-da9d-41ca-a094-31d1fb476b98)
[snipped remainder of truss output]

I'm able to manually create files in this directory, and if I name an empty file to match the above image name `9aa48095-da9d-41ca-a094-31d1fb476b98.zss.gz` it exits without error, indicating the image already exists.

**Comment by cneira** [comment]
Is this happening in the current master branch ?

**Comment by redvelociraptor** [comment]
zcage version reports 1.5.0, which I pulled on Feb 22.

In case it matters, the filesystem of the pool I set it to use is formatted with zfs version 5.

I manually downloaded an image from joyent and placed it in the zcage image directory, and was able to create a new zone, but found another issue I'll file separately.

**Comment by cneira** [comment]
Could you try 1.5.2 (current master)?

**Comment by freezmeinster** [comment]
Hello, i try to clone latest master and this issue still exist. I have very little knowledge about Nodejs and i try to look the code here 
https://github.com/cneira/zcage/blob/c923cfe19d5ee13208dc9f2f85de5b6db5b92a95/lib/imgadm.js#L234
Also on this 
https://github.com/cneira/zcage/blob/c923cfe19d5ee13208dc9f2f85de5b6db5b92a95/lib/imgadm.js#L293
You try to use function fs.writeFileSync without second argument, the "data".

 So i try to change that line from
  `fs.writeFileSync(ZCAGE.IMAGES + '/.test');`
 To
` fs.writeFileSync(ZCAGE.IMAGES + '/.test', 'dummy');`

and it's work

**Comment by cneira** [comment]
@redvelociraptor  I'm really sorry about this bug!, I should have done more complete regression testing after the last refactoring. Let me know if you have any more issues I'm closing this one now.
@freezmeinster  thanks a lot for catching this!.
