### ISSUE TITLE
zcage on Smartos

### ISSUE THREAD

**Issue by marcheschi** [cneira/zcage#7]
Hi
I discovered zcage on twitter and it was a very good surprise for me.
This is what I dreamt for: a way to install docker images on open smartos.
Do you think is possible to adapt it to smartos ?
Thank you for your work
Paolo

**Comment by cneira** [comment]
Hi Paolo, 
For SmartOS you could follow this guide, [I did a couple of months ago and work perfectly]( 
https://blog.jasper.la/docker-on-smartos-the-harder-way.html). [VMADM(1)](https://smartos.org/man/1m/vmadm) is far more complete than zcage, I created zcage just to be able to do a subset of what vmadm is capable of in Omniosce. 
[Also if you need docker you could just install triton and user docker right away](https://docs.joyent.com/public-cloud/instances/docker/how/start-containers) 
https://docs.joyent.com/public-cloud/api/docker
https://docs.joyent.com/private-cloud/install/download

I hope this helps.

**Comment by marcheschi** [comment]
Thank you Carlos
This is very Helpful.
Best Regards
Paolo

**Comment by marcheschi** [comment]
Hi Carlos
I'm so sorry to trouble you again
The triton install was not so easy, and your link docker-on-smartos-the-harder-way is not working anymore.
I followed your work for illumos and I found out that the zcage is still the best idea I've seen so far to use docker or proxmox images.
Do you think that now is possible to use it on plain smartos, or Danubecloud and not in omniosce?
Thank you
Paolo

**Comment by cneira** [comment]
@marcheschi 
have you tried this? https://www.cyber-tec.org/2018/02/11/run-docker-images-on-smartos/

**Comment by marcheschi** [comment]
Thank you @cneira 
I will have a look
Paolo
